### ISSUE TITLE
pSet Properties is not working.

### ISSUE THREAD

**Issue by shailendra26-siso** [IFCjs/components#100]
### Description 📝

https://github.com/IFCjs/components/blob/big-restructure/src/ifc/IfcPropertiesUtils/index.ts#L8
I am working with this feature but not get the success. Can you help me on this please? 
I am using the **Advance IFC JS course for implementation. **

There is error when it's matching the type of property. Somewhere "IFCPROJECT" is matching with type.
Used the Defined the functions for pSet:

![image1](https://github.com/IFCjs/components/assets/119593005/4dc7828c-c52a-4452-83e6-3bc43fc28b89)

![image2](https://github.com/IFCjs/components/assets/119593005/d6f424e7-2cea-4f94-af46-dd883dfd3e8b)

I tried with static expressID but it is also giving the error, see above screenshots.

![image4](https://github.com/IFCjs/components/assets/119593005/99ee4777-81ee-4b71-b1c4-5ab598eea355)

<img width="515" alt="image5" src="https://github.com/IFCjs/components/assets/119593005/c3177ca9-c2e9-4fe8-be65-a46d7c2e02b1">

<img width="436" alt="image6" src="https://github.com/IFCjs/components/assets/119593005/86e11f32-2f76-4dfd-895e-912921b64fdf">

<img width="464" alt="image7" src="https://github.com/IFCjs/components/assets/119593005/bb8e9aeb-788b-445f-ae29-61d849fa6b25">

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @shailendra26-siso can you confirm this is still happening with the latest version? Did you check out the properties tutorial in the documentation?

**Comment by shailendra26-siso** [comment]
Hi,

 

I did not updated the latest version as my work is in mid. Also I am not getting the update regarding library update as I asked you on Discord, that time version was not updated.

If you want then I will try updated version which is launched in last month.

 

Thanks,

 

Shailendra Singh

 



SISO Software’s India Pvt. Ltd.

B-3/61, Safdarjung Enclave, IN-110029 Delhi, India.

Contact: +91-9911682739

 <http://www.siso.net/> www.siso.net

**Comment by agviegas** [comment]
I got it, thanks. Can you please answer in GitHub instead of just answering your email? Reading through the GitHub thread with all the extra text added is hard. Also, we would need a whole minimal application to run it and see what's happening. Thanks in advance!

**Comment by HoyosJuan** [comment]
As this issue is a duplicate from https://github.com/IFCjs/components/issues/101, I will close it.

**Comment by HoyosJuan** [comment]
As this issue is a duplicate from https://github.com/IFCjs/components/issues/101, I will close it.
