### ISSUE TITLE
Issue with fitModeltoFrame function

### ISSUE THREAD

**Issue by keshavanarayan** [IFCjs/components#11]
Hi @harrycollin @agviegas ,

Thank you for the awesome library.
I have not been able to get the fitmodeltoframe function to work on a custom threejs loader. The clipper and dimensions seem to work fine though. I have added a minimum working example here with this issue.

https://github.com/keshavanarayan/viewer/blob/d971453f8065abdb650037faf3a53900764dd11a/src/main.js#L141

Thank you.

**Comment by agviegas** [comment]
Hey @keshavanarayan you can use `camera.controls` to access the [camera controls instance](https://github.com/yomotsu/camera-controls), which will give you all the functions you need to control the camera around.
Also, just FYI, you don't need to tag people in the issues 🙂 cheers!

**Comment by keshavanarayan** [comment]
Sure. Thank you @agviegas
