### ISSUE TITLE
Allow disabling the UI for all components

### ISSUE THREAD

**Issue by danizep** [IFCjs/components#110]
### Description 📝

While using the `FragmentManager` and `FragmentCacher` an unexpected UI appeared when TAB was pressed.

<img width="742" alt="Screenshot 2023-09-14 at 11 06 47" src="https://github.com/IFCjs/components/assets/2084270/96b14df0-1703-4ac7-ae84-63f58af8d47f">

Digging a bit on the code it was possible to understand that UI and listeners are instantiated without actively being requested by the developer.

That said, would be cool to have a way to centrally enable/disable the UI.

### Suggested solution 💡

`components.ui.enabled = false` could centrally specify that the UI should be disabled

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by VictorTrumpel** [comment]
Good idea, i think!

**Comment by acaleph-pz** [comment]
I want to know how the following code ignores IFCSPACE in the new version


```javascript
await ifcLoader.ifcManager.parser.setupOptionalCategories( {
					[ IFCSPACE ]: false,
				} );

```

**Comment by javiercornejo** [comment]
Hello @danizep could you solve this issue?

**Comment by HoyosJuan** [comment]
Hey! This was already implemented in components.uiEnabled. If set to false, no UI at all will be created, so all of them need to be created by the user.

Closing the issue 👍
