### ISSUE TITLE
components.scene.setup() is not a function

### ISSUE THREAD

**Issue by MiguelG97** [IFCjs/components#112]
### Describe the bug 📝

I see this command being used in the tutorial path for setting up the lights: components.scene.setup() 
however, the console shows a message telling me that this command is not a function

![image](https://github.com/IFCjs/components/assets/78984964/86a61c0a-d728-45c8-a1ae-511e61e75f0e)

![image](https://github.com/IFCjs/components/assets/78984964/1518a024-0d3c-4c0d-9a0f-b88833cb0c13)

It has an easy fix [const light = new THREE.AmbientLight(0x404040);      scene.add(light);] from the user side though

### Steps to reproduce 🔢

follow the tutorial path

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MiguelG97** [comment]
same thing with components.renderer.onBeforeUpdate.add()
onBeforeUpdate is undefined
![image](https://github.com/IFCjs/components/assets/78984964/03093c05-3c76-4089-9fd7-c53aada3d416)

![image](https://github.com/IFCjs/components/assets/78984964/0db72051-9933-4ec6-b8fe-fdd183f3d5d7)

**Comment by MiguelG97** [comment]
as well as 
const mainButton = clipper.uiElement.get("main");
why documentation is different from actual npm library:
const mainButton = clipper.uiElement.main;

is it due to a new version package release ?

**Comment by MiguelG97** [comment]
Apparently those commands were coming from the alpha version. I reinstalled the npm package and now I have access to those commands

**Comment by VictorTrumpel** [comment]
what version are you using? I reinstalled the packages but it didn't help me

**Comment by daniel-augusto** [comment]
> ![Screenshot 2023-10-13 at 19 57 42](https://user-images.githubusercontent.com/59663275/274974554-d6d29d73-2ee4-4cfe-a354-d8622d178371.png) what version are you using? I reinstalled the packages but it didn't help me

Please, see comment in this issue https://github.com/IFCjs/components/issues/121
