### ISSUE TITLE
66MB arch IFC file makes the app viewer crash

### ISSUE THREAD

**Issue by MiguelG97** [IFCjs/components#116]
### Describe the bug 📝

Hello folks, 
I've uploaded bigger files than this one (100mb) with items of the same discipline [architecture] but not sure what is the deal with this file as the viewer keeps crashing. 
Can you help me to explore what is causing performance issues with this attached file so we can reorganize the modeling process if it's related to it:
https://drive.google.com/drive/folders/1nQQJVLWHGw0kLYgXPhd6MnKzCfJonYCb?usp=sharing

Regards,
Miguel G.

### Steps to reproduce 🔢

Go to the app viewer:
https://platform.thatopen.com/app

and upload the ifc file attached

### System Info 💻

```shell
AMD Ryzen 5 5600X 6-Core Processor  
3.70 GHz
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gjordanp** [comment]
Same problem here! I have models working on IFC viewer but not in That Open Viewer.
For example, this model: https://spoerering-my.sharepoint.com/:u:/g/personal/gjordan_btd_cl/EbbVWXAMVVdOqMx8DmHvBfMBm1Z1iqgfi6thFNDmrHWiuQ?e=b1V5on

**Comment by agviegas** [comment]
Hey @MiguelG97 @gjordanp! Sorry for the delay, these weeks were really busy, but we are back on track with issues. The issue here is not the size. The current technical ceiling of our technology is 10GB. The problem is that there are some geometric operations that are being stuck in our geometric engine. We have recently made some significant advances, but the links to your models have expired. Is there any chance we can get them again? Thanks a ton in advance!

**Comment by MiguelG97** [comment]
Appreciate the response,
here is the link to the same file:
https://drive.google.com/drive/folders/1dNW-NNSuKd9p0INzeoz7a11h959F_8jq?usp=sharing

regards,

**Comment by agviegas** [comment]
Hum, we are getting a 404 🤔 Was it a temporary link? 

![image](https://github.com/IFCjs/components/assets/56475338/1e98550e-57f7-4260-a416-4b188d8c129a)

**Comment by miguelGTailorbird** [comment]
I thought you've stored in a local drive at this point
Nevermind, here we can find the file
https://drive.google.com/drive/folders/14MwdFBD424vWueki9EVXJQeY43WtzLvs?usp=sharing

all the best!
Miguel

**Comment by MiguelG97** [comment]
I thought you've stored in a local drive at this point
Nevermind, here we can find the file
https://drive.google.com/drive/folders/14MwdFBD424vWueki9EVXJQeY43WtzLvs?usp=sharing

all the best!
Miguel

**Comment by agviegas** [comment]
We've definitely stored it now. Thanks!

**Comment by MiguelG97** [comment]
@agviegas @HoyosJuan
It seems that the rvt model has some defects since Autodesk forge derivative api didn't manage to process the file either.

error response from APS md api:
![image](https://github.com/IFCjs/components/assets/78984964/e4d4d253-dbf4-4d21-9434-10a708cb1f5a)

**Comment by HoyosJuan** [comment]
Allright @MiguelG97! Got it. That means you can open bigger models in the app? Just to know, so we can close this issue 🙂

**Comment by MiguelG97** [comment]
Yes, I believe so
