### ISSUE TITLE
WASD navigation in FPS camera mode in components

### ISSUE THREAD

**Issue by keshavanarayan** [IFCjs/components#12]
Hi @harrycollin @agviegas @MadsHolten @HoyosJuan,

How do I create wasd navigation in fps mode in openbim-components?  The code seems to toggle fps mode but does not provide wasd navigation. Any suggestion will be of great help.

![image](https://user-images.githubusercontent.com/74804559/221392554-8a1a4f92-4db0-43e0-9fd2-bd62c762aca7.png)

**Comment by keshavanarayan** [comment]
Here's my code for reference. https://github.com/keshavanarayan/viewer/blob/2b7b5977b9df3009c54eafe0206ffe9d4a07a8e8/src/main.js#L29

**Comment by agviegas** [comment]
Hey @keshavanarayan you can use `camera.controls` to access the [camera controls instance](https://github.com/yomotsu/camera-controls), which will give you all the functions you need to control the camera around. Again, no need to tag folks in the issue 🙂 Let us know how it goes. Cheers!

**Comment by keshavanarayan** [comment]
Thank you @agviegas. This snippet works. Thank you for the help.


![image](https://user-images.githubusercontent.com/74804559/221451412-8e18da52-3360-413e-8e85-a803754d701b.png)
