### ISSUE TITLE
PrePick Items By ID

### ISSUE THREAD

**Issue by Muhammad-Anus-Developer** [IFCjs/components#125]
### Description 📝

Hi @agviegas, as I transitioned my project from the web-ifc-viewer to components, I used to utilize the following code: await viewer.IFC.selector.prepickIfcItemsByID(0, tagIds, true); in the web-ifc-viewer to enable default selection. However, I've been unable to find a similar feature within the components. Any assistance would be greatly appreciated! 

Thanks in advance

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hi, did you check out the fragments highlighter tutorial? It has methods to highlight by ID, and you can create a style and use it like the prepicking logic of web-ifc-viewer.

**Comment by Muhammad-Anus-Developer** [comment]
Thanks for the response. I'll look into it 🙂
