### ISSUE TITLE
There is no deleteAll methods in Area measurement

### ISSUE THREAD

**Issue by Alia2006** [IFCjs/components#127]
### Describe the bug 📝

![image](https://github.com/IFCjs/components/assets/93459415/9d06662e-ee73-494f-b71e-8e6e18dc2f28)

### System Info 💻

```shell
win11,Chrome
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by emmeongoingammuaroi** [comment]
I had fixed this issue and i would be solved in next version of the library.

**Comment by agviegas** [comment]
This should be fixed already thanks to the kind contribution of @emmeongoingammuaroi. Let us know otherwise!
