### ISSUE TITLE
Please consider removing the auth wall from the documentation

### ISSUE THREAD

**Issue by autra** [IFCjs/components#138]
### Describe the bug 📝

As a dev, I'm using countless of open-source library (and contribute to some). I spend a lot of my time reading documentation from various sources, github organization etc. which are all openly accessible without accounts (which is lucky, because that wouldn't scale).

On the other hand, `components` requires to open an account to read its documentation, which is a hassle, and a bit contradictory with its open-source nature (MIT license), and also with the "open" in "that open company". 

Please consider removing the auth wall and make the documentation truly public. I'd ask a similar thing for the community forum (for read access). 

Thanks for your work!

### Reproduction ▶️

https://platform.thatopen.com/documentation

### System Info 💻

```shell
N/A
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @autra! Excellent point, this makes perfect sense. We will work on this right away and make this happen as soon as possible.
Thanks a lot for this feedback, it really helps us improve. 🙏

**Comment by HoyosJuan** [comment]
Hi @autra! Hope you're doing well.

I'm following up this issue and passing by to let you know the documentation [is already open](https://docs.thatopen.com/).

Thanks for your suggestion!
