### ISSUE TITLE
Visualization of length measurement

### ISSUE THREAD

**Issue by RASRC** [IFCjs/components#147]
### Describe the bug 📝

1) The background color of the label seems to be missing

![Cap01](https://github.com/IFCjs/components/assets/117295504/1ee32bed-c6ad-4913-bc8a-2aa5decbc9cb)

2) When you disable the measurement, it hides only the dimension line. The pointers and the labels are still in the scene.

![Cap02](https://github.com/IFCjs/components/assets/117295504/bb5d6710-8a6f-4a65-a17f-2a1c798a29e9)
![Cap03](https://github.com/IFCjs/components/assets/117295504/5a2fbc34-c3d3-4b7b-aa94-747c05df0c8c)

Thanks!

### Steps to reproduce 🔢

1) Creating a dimension element 

const dimensions = new OBC.LengthMeasurement(this.components)
dimensions.create()

2) Disabling o hiding a dimension element

dimensions.enabled = false;
 dimensions.visible = false;

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @RASRC,
1. Are you importing the CSS styles of the viewer?
2. I'll take a look!

**Comment by RASRC** [comment]
Hi @agviegas. I put the styles that are shown in the documentation inside the main .css file of the app:

![Cap](https://github.com/IFCjs/components/assets/117295504/dac7c962-2c13-46df-9c6f-e6dab3b96626)

About the background color, in the community forum Juan mentioned that could be a color class that was probably deleted in the development process.

I'll be attending to the news. Thanks!

**Comment by HoyosJuan** [comment]
Hi @RASRC! Hope you're fine 🙂

I'm following up this issue. A couple of things:

1. The styles that are referenced in the documentation are not applicable anymore (docs need to be updated about this). 
2. The reason why the background wasn't visible, is because the class that gives its color was missing from the resources/styles.css file just as you said in the previous message.
3. Actually, the fact the measurements still visible is intended (the weird thing is the line hiding when deactivating the tool). In other words, enabling/disabling the tool is not going to hide them, just turn on/off the ability to be created. However, the visibility property does hide them, so we could add another button that works as a visibility toggle. Would that work for you? In fact, I guess it would be a great idea to complement the UI to add a list of current measurements.

The question is: when you toggle `dimensions.visible`, does the dimensions get showed/hidden? If that's the case, then I would close this issue and create a feature issue talking about the button and dimensions window.

Let me know!

**Comment by HoyosJuan** [comment]
Hi @RASRC!

And are you using the built-in UI? Things have changed quite a lot since the IFC.js advance course, and I'm not aware about the BuildingScene class and what exact code should we find there. But, just in case, our conversation means the bug is solved?

**Comment by RASRC** [comment]
Hi @HoyosJuan! Sorry for the late response. I'm starting over the viewer following the Master classes with the latest version of the library.
The appearance now it's ok, but I'm continue having troubles with the visibility when you disable the tool (the labels are still in the scene and not following the scale of the camera’s zoom).

Thanks.

![image](https://github.com/IFCjs/components/assets/117295504/4d1c6721-677b-4a0c-9b20-175e9669f68f)

**Comment by shahbaziparisa** [comment]
> ass and w

Excuse me how did you use the code? Would you please share?
I follow documentation but labels and points are not visible to me. And snapping rectangle is not available.

**Comment by agviegas** [comment]
Hey @shahbaziparisa are you using the library `@thatopen/components`? It should be solved there!

**Comment by shahbaziparisa** [comment]
> Hey @shahbaziparisa are you using the library `@thatopen/components`? It should be solved there!

Yes
Recently I update my project.
Snapping does not work.Do you have sample code?

**Comment by agviegas** [comment]
I don't know if you mean A) "I want to use snapping, and I don't know how" or B) "Snapping doesn't work when using a specific measurement component".

For A), we don't have a specific component for snapping, but you can see how we use it in the source code of the library.
For B), it should work. You can find an example [here](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/measurement/LengthMeasurement/example.ts) and the deployed app [here](https://thatopen.github.io/engine_components/examples/LengthMeasurement/index.html).

We are currently updating the [documentation](https://docs.thatopen.com/intro). Hopefully later today you will be able to find all the updated tutorials for measurement components as well.

**Comment by shahbaziparisa** [comment]
> I don't know if you mean A) "I want to use snapping, and I don't know how" or B) "Snapping doesn't work when using a specific measurement component".
> 
> For A), we don't have a specific component for snapping, but you can see how we use it in the source code of the library. For B), it should work. You can find an example [here](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/measurement/LengthMeasurement/example.ts) and the deployed app [here](https://thatopen.github.io/engine_components/examples/LengthMeasurement/index.html).
> 
> We are currently updating the [documentation](https://docs.thatopen.com/intro). Hopefully later today you will be able to find all the updated tutorials for measurement components as well.

Thanks. I need such snapping to corner on .ifc models . I load ifc model and use the same code but magnetic snapping to corners is not available. For me, a red rectangle appear but never snapped to corners

**Comment by agviegas** [comment]
If you are trying to use the measurement tools provided by the library, today I'll update the documentation on them. They will include a full working example (including snapping). 

If you are trying to make just snapping work on your end for other purposes, I suggest you copy the same code we use to your project, understand it and debug it to see why it's not working for you.

**Comment by shahbaziparisa** [comment]
> You are right, snapping is not working for IFC models. I'll fix this today!

Hi
Is it fixed now?

**Comment by agviegas** [comment]
Yes, it should be fixed in the latest patch.
