### ISSUE TITLE
Create feature snapshot 

### ISSUE THREAD

**Issue by DinhqTu** [IFCjs/components#151]
### Description 📝

Create a button that when clicked will take a screenshot including model, grid and markup.

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by thomasrabl1** [comment]
Till this feature is avaible i was able to get a snapshot of the model with:
```
let scene = component.scene.get();
let camera = component.camera.get();
let renderer = component._renderer._renderer;
renderer.render(scene, camera)
let modelImg = renderer.domElement.toDataURL();
```

**Comment by DinhqTu** [comment]
i got it. thanks sir

**Comment by agviegas** [comment]
Thanks a ton, @thomasrabl1! Indeed, that way a snapshot can be obtained. We could provide a method to do that, but as it can be done in just 5 lines of code, it's probably not worth it to do it. I'm closing this issue for now: if there's a need to make a snapshot that requires more code or more complex logic, let us know and we'll take a look at it!
