### ISSUE TITLE
Changing navigation between FirstPerson and Orbit or Pan breaks Orbit/Pan

### ISSUE THREAD

**Issue by radoslawflis** [IFCjs/components#184]
### Describe the bug 📝

There is a problem when changing navigation from first person to orbit and vice versa. First person breaks orbit. 
I tested it out in my app and seems to have exactly the same problem when applying 1.FirstPerson 2.Orbit, Orbit doesn't work properly, the pivot point is still the same.
Basically, FirstPerson navigation breaks Orbit navigation or Pan (you called it Plan) navigation.

Test it out in the app:

cameraComponent.setNavigationMode('Orbit');
cameraComponent.setNavigationMode('FirstPerson');
![image](https://github.com/IFCjs/components/assets/125380891/39abacbb-80f0-4806-a9f2-43a70cf4858c)
The same issue is on the official open platform as on the picture

### Steps to reproduce 🔢

1. Set Navigation to mode First Person
2. Switch to navigation mode Orbit or Pan
In case of Orbit there will be problem with pivot point, in case of pan there will be issue with speed of truck movement (to slow)

### System Info 💻

```shell
{
  "name": "ifc-model",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.0.0"
  },
  "dependencies": {
    "bootstrap": "^5.2.3",
    "camera-controls": "^2.7.3",
    "openbim-components": "1.1.1",
    "three": "^0.152.2"
  }
}
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
This has been solved in PR https://github.com/IFCjs/components/pull/236.
