### ISSUE TITLE
Auto include CSS styles from CDN

### ISSUE THREAD

**Issue by HoyosJuan** [IFCjs/components#189]
### Description 📝

Currently, people need to download from **resources/styles.css** the styles applied to the UI Components in the library. The goal is to do it automatically when the UIManager gets initialized. Would need to keep in mind to include an option to not do it if the developer doesn't want to use the built-in user interface.

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Implemented in PR https://github.com/IFCjs/components/pull/218.

**Comment by quasarchimaere** [comment]
see issue #322 this is not a good "feature" this is a tracking device and might lead to people not being able to use obc
