### ISSUE TITLE
Coordinate fragments when loaded with FragmentManager

### ISSUE THREAD

**Issue by HoyosJuan** [IFCjs/components#190]
### Description 📝

At the time being, the models are just coordinated between them if they are uploaded directly from FragmentIfcLoader. The goal is to allow the fragments to also be self-coordinated when upload it directly with FragmentManager.

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by PabloAballe** [comment]
Hello,

The same thing is happening to me in my project once I pass everything to fragments and then try to load these fragments the different ifc models do not align correctly.

<img width="955" alt="image" src="https://github.com/IFCjs/components/assets/51853263/b675f1b2-b28c-4d0c-a6d2-9cb1012d2b33">


All the best
