### ISSUE TITLE
Setting uiEnabled = false on Components instance cause a lot of errors

### ISSUE THREAD

**Issue by nextdesusu** [IFCjs/components#204]
### Describe the bug 📝

Hello i would like to use this library without provided ui and when i tried to do it i suddenly get a lot of errors, and my model for example lost all colors. 

### Steps to reproduce 🔢

    const components = new Components();
    components.uiEnabled = false;
    
    after this proceed to initialise components and setup a scene. 

### System Info 💻

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 22.10 GB / 31.16 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nextdesusu** [comment]
Oh sorry if im caused problems by this issue i just spotted there is a feature request to allow to use this library without ui, i thought it already implemented, but i seem to be mistaken.

**Comment by HoyosJuan** [comment]
Hi @nextdesusu! Could you please:

1. Share some of the errors you're getting.
2. The openbim-component version you're using.

Thanks a lot!

**Comment by HoyosJuan** [comment]
Hey @nextdesusu! How is it going with this issue? If you update the library to the latest version (1.2.0), are you still getting the errors?

**Comment by nextdesusu** [comment]
@HoyosJuan oh sorry had to do different project which doesnt involve this library, im going to check this in monday, thank you

**Comment by nextdesusu** [comment]
@HoyosJuan it seems bug been fixed thank you!
