### ISSUE TITLE
Culling buggy when many part-models loaded

### ISSUE THREAD

**Issue by vulevukusej** [IFCjs/components#212]
### Describe the bug 📝

Possibly related to #209.  I have 18 files which are all seperate building stories from the same project.  As i orbit around the model, whole sections of the model dissappear, even though they shouldn't be culled.  Unfortunately, I couldn't test this on [that open viewer](https://platform.thatopen.com/app), because of #209, but the screens below demonstrate the behavior. 

![image](https://github.com/IFCjs/components/assets/83825269/129636b4-6f11-4ed2-9e12-8fc671bda8e3)
![image](https://github.com/IFCjs/components/assets/83825269/be2fd0cd-daf0-4825-8dd1-4095daad7aa7)

Files have been privately shared to antonio@thatopen.com

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vulevukusej** [comment]
Update: I changed the guids myself so that I could load the part models onto https://platform.thatopen.com/app.  The same issue is persistent (even worse?).

![image](https://github.com/IFCjs/components/assets/83825269/827ed19b-aaad-41ef-8e77-e12ca7ca7e81)

**Comment by agviegas** [comment]
File privately available [here](https://drive.google.com/file/d/128BTRDbxNoy1KC2NwtuIAIc9iUcNYQKj/view?usp=drive_link).
