### ISSUE TITLE
How to add ifc model in react-map-gl layer.

### ISSUE THREAD

**Issue by force9493** [IFCjs/components#216]
### Description 📝

I am working on the map-relevant project now. I am using react-map-gl to display the map. Also, I want to display the IFC model with this library. But I can't display the model because the renderer is different. 

Also, FragmentIfcLoader is not working with the error log "uiElement isn't initialized".
Please help me to resolve this problem, if anyone has an experience of this similar problem.

**Comment by HoyosJuan** [comment]
Hey @force9493! Hope you're doing well 🙂

We try to keep the issues in the repository to report specific bugs or to propose features. To make questions about the library and get help, I invite you to access the community at https://people.thatopen.com/, it's free and there are many people willing to help others!!

I will close this issue, thank you! 🙏
