### ISSUE TITLE
[SimpleGrid] To be able to control grid height (positioning)

### ISSUE THREAD

**Issue by edgar-g-q** [IFCjs/components#225]
### Description 📝

I am using this library to load different ifc files using FragmentManager and FragmentIfcLoader. Also, I am using a SimpleGrid, and my goal is to have a grid aligned with the base of each model (the lowest z coordinate I assume).
I believe that currently it is not possible to control the positioning of the SimpleGrid.

### Suggested solution 💡

I suggest to add an extra parameter to the SimpleGrid constructor in order to control the positioning of the grid.

In order to implement that, I think it is possible to access the generated Mesh position after [this line](https://github.com/IFCjs/components/blob/1e2695e38b07885d7168f83382e027189c5f6e56/src/core/SimpleGrid/index.ts#L175).
I think it should be possible to update this position here.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by NiklasPor** [comment]
Funny, I just implemented this for myself 👀 

1. We need a method to update the y coordinate of the grid mesh
```ts
  private updateMinY = () => {
    const minY = Math.min(...this.fragments.groups.map((group) => group.boundingBox.min.y));
    this._grid.position.y = minY;
  };
```

2. We need to call the method whenever the fragments change. For me the on load when an ifc model was opened was enough:
```ts
  // Inside setupEvents 
    if (active) {
      this.fragmentLoader.onIfcLoaded.add(this.updateMinY);
    } else {
      this.fragmentLoader.onIfcLoaded.remove(this.updateMinY);
    }
 ```

![image](https://github.com/IFCjs/components/assets/13211347/4e2fe41c-6d01-4445-857e-f6c0a9109761)

**Comment by HoyosJuan** [comment]
Hey @NiklasPor, thanks for your help!

@edgar-g-q, does Niklas answer help you? So I can close this issue?

**Comment by edgar-g-q** [comment]
Hey, thanks for the proposal. However, I think it is necessary to implement this in your library, as grid is a private property, and I can't access it from my code. The solution looks good though.

**Comment by NiklasPor** [comment]
```ts
const grid = new OBC.SimpleGrid(components);
const grid mesh = grid.get()
```

`.get()` will return you the `_grid` variable. Or you just copy the whole implementation if you want to change even more 👀

**Comment by edgar-g-q** [comment]
I will try it right now, thanks :)

**Comment by edgar-g-q** [comment]
The solution proposed works perfectly! I think the issue can be closed
