### ISSUE TITLE
ifcloader for react three fiber

### ISSUE THREAD

**Issue by dberardo-com** [IFCjs/components#246]
### Description 📝

not clear how to use this project as a loader for react three fiber

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey @dberardo-com! Thanks for reaching here 🙂

We try to keep issues here at GitHub as clean as possible, so that involves using it to report problems/asking features. Please, for questions join us for free at https://people.thatopen.com/home. Hope to see you there!

Closing the issue.

**Comment by dberardo-com** [comment]
well, things is. this issue might still considered as such, because it concerns missing documentation. i think documentation is indeed missing on how to use this library's loader in both threejs and react3f,

i will also link this issue to the slack channel

**Comment by RyugaRyuzaki** [comment]
> well, things is. this issue might still considered as such, because it concerns missing documentation. i think documentation is indeed missing on how to use this library's loader in both threejs and react3f,
> 
> i will also link this issue to the slack channel

https://people.thatopen.com/c/how-i-ve-done-it/integrate-react-three-offscreencanvas
