### ISSUE TITLE
Different behaviour when using FragmentIfcLoader twice

### ISSUE THREAD

**Issue by FlorianB-DE** [IFCjs/components#251]
### Describe the bug 📝

When using the FragmentIfcLoader we get different behaviour when the same model is uploaded a second time. 

### Reproduction ▶️

https://ifcjs.github.io/components/src/fragments/FragmentIfcLoader/index.html

### Steps to reproduce 🔢

1. Upload IFC file (in my case I used the [BuildingSmart demonstrator model](https://raw.githubusercontent.com/buildingSMART/Sample-Test-Files/master/IFC%202x3/Duplex%20Apartment/Duplex_A_20110907.ifc) but I tested it with other models too)
2. wait till it's imported. It should have "bounding boxes" like so:
![image](https://github.com/IFCjs/components/assets/41265177/779a34cc-6ee0-4f33-98ea-1d6452f0dd58)
3. click on "Dispose fragments"
4. upload the same model again
5. the boxes are gone:
![image](https://github.com/IFCjs/components/assets/41265177/b5f25a0b-f990-42fe-94f2-780e099367aa)

### System Info 💻

```shell
System: Windows 11, RTX 2080 Super, AMD Ryzen 5 2600X
Binaries: Provided with the Website (Version: 0.0.46)
Browser: LibreWolf (Firefox) 113.0.2-1 (with WebGL turned on)
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

``` javascript
Object { IfcAlignment: [], IfcCrossSection2D: [], IfcCrossSection3D: [] }
[openbim-components.js:100659:17](https://ifcjs.github.io/components/resources/openbim-components.js)
Object { isObject3D: true, uuid: "1xS3BCk291UvhgP2a6eflL", name: "Duplex_A_20110907.ifc", type: "Group", parent: null, children: (93) […], up: {…}, position: {…}, rotation: {…}, quaternion: {…}, … }
[index.html:272:17](https://ifcjs.github.io/components/src/fragments/FragmentIfcLoader/index.html)
Loading the IFC took 816.683 ms!
```

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hi @FlorianB-DE! Following up this issue.

The reference to the buildingSMART model you're talking about points to the same example page of components. May you please update the link so I can try to reproduce this using the same model? 

Thanks!

**Comment by FlorianB-DE** [comment]
Hi @HoyosJuan. Thanks for noticing. Should be fixed. In case not: https://raw.githubusercontent.com/buildingSMART/Sample-Test-Files/master/IFC%202x3/Duplex%20Apartment/Duplex_A_20110907.ifc
But I have this issue with any arbitrary ifc file..
