### ISSUE TITLE
how to make mapbox and ifc view together？

### ISSUE THREAD

**Issue by kanbang** [IFCjs/components#258]
### Description 📝

 I am interested in exploring the integration of Mapbox with IFC Viewer. I understand the individual functionalities of both platforms but am looking for guidance on how to effectively combine them. Are there any recommended practices or examples of successful integrations? What are the potential challenges and how can they be overcome? Additionally, I would appreciate any insights into the performance implications of such an integration, especially regarding data rendering and interactivity.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
HI @kanbang! Thanks for your participation.

We try to keep the issues in GitHub to only report bugs and propose new features. To make any kind of question like the one you're doing, we encourage people [join our free community](https://people.thatopen.com/) and [ask anything they like](https://people.thatopen.com/c/conversations/). I hope to see you there!

Thanks a lot.
