### ISSUE TITLE
VR viewer

### ISSUE THREAD

**Issue by danieleCTM** [IFCjs/components#282]
Is it possible to use WebXR to develop a BIM enabled VR viewer that allows to see informations about the model?
I might be wrong, but I seem to understand that the rendering engine is somehow limited to this day? I am referring to this [issue](https://github.com/IFCjs/components/issues/264)

**Comment by HoyosJuan** [comment]
Yes, it's completely possible. ThreeJS has a built-in [WebXRManager](https://threejs.org/docs/?q=web#api/en/renderers/WebGLRenderer.xr) in the WebGLRenderer. If you're using either of the built-in renderers in components (SimpleRenderer and PostproductionRenderer), then you can access the WebGLRenderer with the get method.

**Comment by christiandimitri** [comment]
@HoyosJuan i tired to set it up, at sessionInit the camera stereo gets confused and the navigator doesn't connect with the webxr emulator api

**Comment by HoyosJuan** [comment]
@christiandimitri. do you get any errors?

**Comment by danieleCTM** [comment]
> Yes, it's completely possible. ThreeJS has a built-in [WebXRManager](https://threejs.org/docs/?q=web#api/en/renderers/WebGLRenderer.xr) in the WebGLRenderer. If you're using either of the built-in renderers in components (SimpleRenderer and PostproductionRenderer), then you can access the WebGLRenderer with the get method.

what do you mean with "get method" ?

**Comment by christiandimitri** [comment]
@HoyosJuan i get no errors at all, let me check my project and let u know, i have left behins since that thread is opened, thanks for your assistance.
