### ISSUE TITLE
Unable to set visibility for post-production effect

### ISSUE THREAD

**Issue by aka-blackboots** [IFCjs/components#36]
https://github.com/IFCjs/components/blob/8969ecb0652d7b8130254262e7397b269a08a6e1/src/navigation/PostproductionRenderer/index.html#L81-L82

On trying to set `components.renderer.postproduction.visible = false` the post-production is still rendered. 

Also, having a single boolean that can enable or disable the effect will make it easy to handle.

**Comment by agviegas** [comment]
I've substituted the postproduction effect by a better one. This shouldn't be a problem anymore!
