### ISSUE TITLE
Double-sided materials

### ISSUE THREAD

**Issue by MadsHolten** [IFCjs/components#4]
DoubleSided materials are not rendered correctly.

<img width="524" alt="Issue" src="https://user-images.githubusercontent.com/13613073/209325128-eec257d3-e21a-4529-96c6-5f4d5481aca9.png">

Below you see an example of the glTF taken directly from the zip loaded in an [online viewer](https://gltf-viewer.donmccurdy.com/) and here there is no problem.
![image](https://user-images.githubusercontent.com/13613073/209325224-8db809d3-faad-45d0-9cb3-2f9c614baecd.png)

The following fragments zip can be used for testing:
[Duplex.zip](https://github.com/IFCjs/components/files/10294540/Duplex.zip)

I tried making the following changes to `fragment-ifc-importer/geometry.ts` with no luck
```typescript
private sortGeometriesByMaterials(
    geometryData: WEBIFC.PlacedGeometry,
    geometry: THREE.BufferGeometry
  ) {
    const materialID = this.saveMaterials(geometryData);
    if (!this._geometriesByMaterial[materialID]) {
      this._geometriesByMaterial[materialID] = [geometry];
    } else {
      this._geometriesByMaterial[materialID].push(geometry);
    }
    geometry.computeVertexNormals(); <----ADDED
  }

private saveNewMaterial(colorID: string, color: WEBIFC.Color) {
    console.log("SaveNewMat")
    this._materials[colorID] = new THREE.MeshLambertMaterial({
      color: new THREE.Color(color.x, color.y, color.z),
      transparent: color.w !== 1,
      opacity: color.w,
      side: THREE.DoubleSide <----ADDED
    });
}
```

**Comment by MadsHolten** [comment]
Probably the problem is with bim-fragment. I will try solving it here: https://github.com/IFCjs/fragment/blob/main/library/src/fragment-loader.ts

**Comment by MadsHolten** [comment]
I managed to fix it myself. In order to fully fix the problem one will have to 1) Implement [this PR in fragments](https://github.com/IFCjs/fragment/pull/2), 2) Publish a new version of fragments on npm, 3) Implement [this PR](https://github.com/IFCjs/components/pull/5) and 4) Bump the version of fragments used here.

**Comment by agviegas** [comment]
Hey, sorry for the late reply, I missed this. I think that with the current implementation, you can set all the materials of a fragment set to be double sided by just traversing them and setting them as such. Don't you think this is better, as double sided materials have a higher computational cost? That way, the scene will be more efficient by default, and only people that need double sides will be able to set it up.

**Comment by agviegas** [comment]
Closing this for now, but open to discussing this further!
