### ISSUE TITLE
Link to documentation (in readme) doesn't work

### ISSUE THREAD

**Issue by Timdelouw** [IFCjs/components#56]
### Describe the bug 📝

Hello,

When I click the link "documentation" on the page below, I receive the error: "page not found". 

https://github.com/IFCjs/components 

Can this link be changed to a working one?

Best regards,

Tim de Louw

### Reproduction ▶️

https://github.com/IFCjs/components

### System Info 💻

```shell
-
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi, thanks for the notice! The documentation for this library is not public yet. We will publish it this summer. In the meantime, I've removed the link from the library page, and will put it back when we publish it.
