### ISSUE TITLE
Wrong coordinates of each models

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [IFCjs/components#68]
### Describe the bug 📝

when model is federated, the coordinates system is not refer to the model origin.
![20230614_wrong_coordinates_of_each_models](https://github.com/IFCjs/components/assets/137836321/4d5efd4b-4280-45d4-8179-46d5a4a622b0)

### System Info 💻

```shell
--
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @ThatMetaverseArchitect  I think we have solved this. Can you please resend the link for this models to my mail to make sure this is already solved? Thanks!
