### ISSUE TITLE
Issues with geometry of an IFC

### ISSUE THREAD

**Issue by FirebirdCS** [IFCjs/components#78]
### Describe the bug 📝

Hi I finished the advanced course of IFC.js using react. I managed to load differents IFC without errors except this one. There is parts of the IFC that are missing from the model. If I use the web-ifc demo the parts are showing perfectly. I'm using the latest openbim-components package showed in the course (0.0.51) that has web-ifc version 0.0.36.

![247638326-74bc956e-c25c-4e1c-a15e-53d7cfe56e0a](https://github.com/IFCjs/components/assets/70920440/e1d17e8c-4148-4039-91fd-eb0245fb5a04)
![247638343-08e6c9ff-4082-450b-9c49-bf61a463b8f5](https://github.com/IFCjs/components/assets/70920440/1a428b3a-506e-4f46-aa4a-fe2956e5eb5c)

### System Info 💻

```shell
--
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

--

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @FirebirdCS any chance I can get access to that model to take a look? Thanks in advance!

**Comment by HoyosJuan** [comment]
Hi @FirebirdCS! Are you experiencing the same problems if you update to openbim-components@1.1.5?

**Comment by FirebirdCS** [comment]
Sorry for not replying but in the new app viewer it shows perfectly the IFC. Thank you!
![image](https://github.com/IFCjs/components/assets/70920440/9443a989-2b8b-4990-974c-6ac0c29d08a1)
