### ISSUE TITLE
Issue within loading two o more IFC models with the same coordinates.

### ISSUE THREAD

**Issue by FirebirdCS** [IFCjs/components#79]
### Describe the bug 📝

Hi I finished the advanced course of IFC.js. In the viewer I'm loading two models which has the same coordinates but it doesn't show an alignment between them in the viewer. I tested these two models in BIM Collab Zoom (second picture)  and it shows like I expect. I tested these two models in the web-ifc-viewer demo and it shows like I expect (third picture). I'm using the latest openbim-components package showed in the course (0.0.51) that has web-ifc version 0.0.36. 
![ifcmodel1](https://github.com/IFCjs/components/assets/70920440/5fd0fa6f-9962-4923-9d88-e40137c602b2)
![BIMCollab](https://github.com/IFCjs/components/assets/70920440/06134a75-2f09-4b2b-be7f-027a8a156ec4)
![ifcmodel2](https://github.com/IFCjs/components/assets/70920440/97a7e2b5-640e-4d6d-93a3-e777533759b0)

### Steps to reproduce 🔢

--

### System Info 💻

```shell
--
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

-

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hi @FirebirdCS! Are you experiencing this same problem when updating to openbim-components@1.1.5?

**Comment by FirebirdCS** [comment]
Hi sorry for not replying but I tested these two IFCs in the new app viewer and it shows correctly now. Thank you!
![image](https://github.com/IFCjs/components/assets/70920440/d7506743-2b29-45ed-ab65-93f2271e84c9)
