### ISSUE TITLE
FragmentProperties.add fails when if not all properties have a "type

### ISSUE THREAD

**Issue by vulevukusej** [IFCjs/components#81]
### Describe the bug 📝

The following line will fail if for some reason the item doesn't have type.  This could happen if web-ifc reports` Invalid IFC Line: #####`

![image](https://github.com/IFCjs/components/assets/83825269/cd5208b2-4229-4203-8783-8936a0867b06)

### System Info 💻

```shell
openbim-components": "1.0.0-alpha.42",
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @vulevukusej can we get an IFC file where we can reproduce this? Thanks in advance!

**Comment by vulevukusej** [comment]
Hey @agviegas.  This was a while ago and I haven't had issues since.  I'll close until it appears again.
