### ISSUE TITLE
Error in Floorplans views

### ISSUE THREAD

**Issue by RASRC** [IFCjs/components#92]
### Describe the bug 📝

When the app uses the floorplan navigator, it doesn’t work like it should be. I saw in the documentation that the elevation it’s defined by the SceneHeigth parameter, but when the fragments are generated in the model, this value is always the same. Even throw I change the elevation calculation by using the Elevation.value parameter, it takes me to a wrong level. What can be happening? Thanks!
![Cap01](https://github.com/IFCjs/components/assets/117295504/3aee1536-1842-495d-8e2c-43278ab8fea2)
![Cap02](https://github.com/IFCjs/components/assets/117295504/610fc52b-e0ad-47c8-b842-4a6710e270b2)

### Reproduction ▶️

https://github.com/RASRC/Pruebas_Varias

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @RASRC can you please let me know where that is stated in the docs? Does this still happen? If so, is there any chance you could provide an IFC privately so that we can fix it? Thanks in advance!

**Comment by RASRC** [comment]
Hi @agviegas. After testing the Floorplan Viewer with the new version of the library it appears to work fine.
Thanks for the response!
